server:
  port: 80

spring:
 #网关
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:  "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: item_rout
          uri: lb://service-item
          predicates:
            - Path=/lock/add

        - id: cart_rout
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**

        - id: order_rout
          uri: lb://service-order
          predicates:
            - Path=/api/order/**

        - id: pay-route
          uri: lb://service-pay
          predicates:
            - Path=/api/payment/**

        - id: user-route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**


        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com

app:
  auth:
    no-auth-url:
      - /css/**
      - /js/**
      - /img/**
      - /login.html
      - /api/user/passport/login
    login-auth-url:
      - /trade.html
      - /api/**/auth/**
    deny-url:
      - /api/inner/**
    login-page: http://passport.gmall.com/login.html

