server:
  port: 80

spring:
 #网关
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:  "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
        - id: item-rout
          uri: lb://service-item
          predicates:
            - Path=/lock/add

        - id: user-route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com

