server:
  port: 8000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web
  redis:
    host: 192.168.200.100
    password: haqq123456

app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  httpclient:
    enabled: true
  client:
    default:
      ConnectTimeOut: 10000
      ReadTimeOut: 10000